### PR TITLE
[PRM-2787] Removed Empty Enum

### PR DESCRIPTION
**Pull request by JBlacklaws**

### CODE REVIEW

**Comment by RoheelArshad** [comment]
Shouldn't we continue to support " " as R5B is not released yet?

**Comment by JBlacklaws** [comment]
> Shouldn't we continue to support " " as R5B is not released yet?I could put [this section](https://github.com/hmrc/penalties/pull/283/files#diff-7482eee457db0a1e4f4d9e43c03e5838b942a04dc8849e22bcd397537a8497b2R42) behind the feature switch, but isn't this ticket specifically about removing the blank value?

**Review by LewisMitchell — DISMISSED** [review]

**Comment by RoheelArshad** [comment]
We just have to make sure " " is still acceptable with this PR, as " " is a legitimate case

**Comment by JBlacklaws** [comment]
> We just have to make sure " " is still acceptable with this PR, as " " is a legitimate case

We're not doing this for the other PRs, are we? I could change line 43 in AppealInformationType to:
`if ((appealInformation.appealLevel.isEmpty || appealInformation.appealLevel.contains(AppealLevelEnum.Empty))` but I feel that would be out of step with the other changes we've made

**Review by RoheelArshad — APPROVED** [review]

**Pull request merged**
